Correct plural, singular forms #244
darrenburns/ward pull request #258
Opened 2021-06-08 17:43 UTC by asadafasab

Fixing plural and singular forms.
I used multi-line string because of the line length.

2021-06-08 17:56 UTC, asadafasab commented
![example](https://user-images.githubusercontent.com/33875895/121234005-890cd780-c893-11eb-8fe4-12c9e58d69c8.png)

2021-06-09 19:10 UTC, darrenburns commented
Thanks for this!

I think we could probably avoid using multiline strings here if we extract some variables similar to this:

```python
        test_plural = "test" if self.num_tests_collected == 1 else "tests"
        fixture_plureal = "fixture" if self.num_fixtures_collected == 1 else "fixtures"
```

and then inject those into the f-string.

We can also change the `[/b]` to `[/]`. It's a shorthand offered by the Rich library for closing tags.

Let me know if you have any questions :)

2021-06-10 14:44 UTC, asadafasab commented
Thanks, but for coherence, I'll stick to `[/b]`.

2021-06-10 14:52 UTC, darrenburns requested changes

2021-06-10 14:52 UTC, darrenburns commented on ward/_terminal.py
> +        fixture_plureal = "fixture" if self.num_fixtures_collected == 1 else "fixtures"
```suggestion
        fixture_plural = "fixture" if self.num_fixtures_collected == 1 else "fixtures"
```

2021-06-10 14:52 UTC, darrenburns commented on ward/_terminal.py
> +            f"and [b]{self.num_fixtures_collected}[/b] {fixture_plureal} "
```suggestion
            f"and [b]{self.num_fixtures_collected}[/b] {fixture_plural} "
```

2021-06-10 15:03 UTC, asadafasab commented
Sorry

2021-06-10 15:14 UTC, darrenburns commented
Thanks for the contribution! I'm not sure why the Codecov report is failing. It's been happening all day and isn't related to your changes.

2021-06-10 15:15 UTC, merged